routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'SiteController@index');

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('home');
Route::get('/product/delete/{id?}', 'ProductController@delete')->name('product.delete');
Route::get('/product/edit/{id?}', 'ProductController@edit')->name('product.edit');

Route::resource('product', 'ProductController');

app/Log.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Log extends Model
{
    //
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    //
    use ProductLog;
    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

}

app/ProductBidHistory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProductBidHistory extends Model
{
    //
}

app/ProductLog.php
<?php

namespace App;

trait ProductLog
{
    protected static function boot()
    {
        parent::boot();
        Product::created(function ($product)
        {
            self::saveLog($product, 'created');
        });

        Product::deleted(function ($product)
        {
            self::saveLog($product, 'deleted');
        });

        Product::updated(function ($product)
        {
            self::saveLog($product, 'updated');
        });
    }

    protected static function saveLog($product, $action)
    {
        $log = New Log();
        $log->product_id = $product->id;
        $log->user_id = \Auth::id();
        $log->type = $action;
        $log->save();
    }
}

app/ProductViewHistory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProductViewHistory extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderBy('updated_at', 'desc')->get();
        return view('dashboard',  ['products' => $products]);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Mockery\Exception;

class ProductController extends Controller
{

    /**
     * ProductController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        $products = Product::orderBy('updated_at', 'desc')->get();
        return view('product/list',  ['products' => $products]);
    }
    /**
     * Show the form for creating a Product.
     *
     * @return Response
     */
    public function create()
    {
        return view('product/create');
    }

    /**
     * Create a new flight instance.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        // Validate the request...
        try {
            $this->validate($request, [
                'name' => 'required|max:500',
                'sku' => 'required|unique:products|max:55',
                'description' => 'required',
                'price' => 'required|numeric',
            ]);

            $product = new Product();

            $product->name = $request->name;
            $product->sku = $request->sku;
            $product->price = $request->price;
            $product->description = $request->description;

            if ($product->save())
            {
                Session::flash('message', 'Product created successfully!');
                return redirect()->action('DashboardController@index');
            }
        }
        catch (Exception $e)
        {
            Session::flash('message', $e->getMessage());
        }
    }


    /**
     * Update the specified Product in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
        $product = Product::find($id);
        if(!$product)
        {
            Session::flash('message', 'Product not found');
            return redirect()->action('DashboardController@index');
        }
        return view('product/edit',  ['product' => $product]);
    }

    public function update(Request $request, $id)
    {
        $product = Product::find($id);

        $this->validate($request, [
            'name' => 'required|max:500',
            'sku' => 'required|unique:products,sku,'.$product->id.'|max:55',
            'description' => 'required',
            'price' => 'required|numeric',
        ]);


        $product->name = $request->name;
        $product->sku = $request->sku;
        $product->price = $request->price;
        $product->description = $request->description;

        if ($product->save()) {
            Session::flash('message', 'Product saved successfully!');
            return redirect()->action('DashboardController@index');
        }

    }

    /**
     * Delete the specified Product
     *
     * @param  int  $id
     * @return Response
     */
    public function delete($id)
    {
        $product = Product::find($id);
        if($product->delete())
        {
            Session::flash('message', 'Product deleted successfully!');
        }
        return redirect()->action('DashboardController@index');
    }

}

app/Http/Controllers/SiteController.php
<?php

namespace App\Http\Controllers;
use App\Product;
use Illuminate\Http\Request;

class SiteController extends Controller
{
    //
    public function index()
    {
        $products = Product::orderBy('updated_at', 'desc')->simplePaginate(10);
        return view('landing',  ['products' => $products]);
    }
}

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
    @if (session('message'))
        <div class="alert alert-info">
            {{ session('message') }}
        </div>
    @endif

    <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li class="active">Dashboard</li>
    </ol>

    <h2 class="page-header">Products</h2>
    @include('product.list')

    <h2 class="page-header">Latest Bids</h2>
    <div class="table-wrapper">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Product name</th>
                    <th>Bid email</th>
                    <th>Bid amount</th>
                    <th>Bid time</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1,001</td>
                    <td>Lorem</td>
                    <td>ipsum</td>
                    <td>dolor</td>
                    <td>sit</td>
                </tr>
                <tr>
                    <td>1,002</td>
                    <td>amet</td>
                    <td>consectetur</td>
                    <td>adipiscing</td>
                    <td>elit</td>
                </tr>
                <tr>
                    <td>1,003</td>
                    <td>Integer</td>
                    <td>nec</td>
                    <td>odio</td>
                    <td>Praesent</td>
                </tr>
                <tr>
                    <td>1,003</td>
                    <td>libero</td>
                    <td>Sed</td>
                    <td>cursus</td>
                    <td>ante</td>
                </tr>
                <tr>
                    <td>1,004</td>
                    <td>dapibus</td>
                    <td>diam</td>
                    <td>Sed</td>
                    <td>nisi</td>
                </tr>
                <tr>
                    <td>1,005</td>
                    <td>Nulla</td>
                    <td>quis</td>
                    <td>sem</td>
                    <td>at</td>
                </tr>
                <tr>
                    <td>1,006</td>
                    <td>nibh</td>
                    <td>elementum</td>
                    <td>imperdiet</td>
                    <td>Duis</td>
                </tr>
                <tr>
                    <td>1,007</td>
                    <td>sagittis</td>
                    <td>ipsum</td>
                    <td>Praesent</td>
                    <td>mauris</td>
                </tr>
                <tr>
                    <td>1,008</td>
                    <td>Fusce</td>
                    <td>nec</td>
                    <td>tellus</td>
                    <td>sed</td>
                </tr>
                <tr>
                    <td>1,009</td>
                    <td>augue</td>
                    <td>semper</td>
                    <td>porta</td>
                    <td>Mauris</td>
                </tr>
                <tr>
                    <td>1,010</td>
                    <td>massa</td>
                    <td>Vestibulum</td>
                    <td>lacinia</td>
                    <td>arcu</td>
                </tr>
                <tr>
                    <td>1,011</td>
                    <td>eget</td>
                    <td>nulla</td>
                    <td>Class</td>
                    <td>aptent</td>
                </tr>
                <tr>
                    <td>1,012</td>
                    <td>taciti</td>
                    <td>sociosqu</td>
                    <td>ad</td>
                    <td>litora</td>
                </tr>
                <tr>
                    <td>1,013</td>
                    <td>torquent</td>
                    <td>per</td>
                    <td>conubia</td>
                    <td>nostra</td>
                </tr>
                <tr>
                    <td>1,014</td>
                    <td>per</td>
                    <td>inceptos</td>
                    <td>himenaeos</td>
                    <td>Curabitur</td>
                </tr>
                <tr>
                    <td>1,015</td>
                    <td>sodales</td>
                    <td>ligula</td>
                    <td>in</td>
                    <td>libero</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/landing.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ config('app.name', 'Easy Bids') }}</title>
    <link rel="stylesheet" href="{{ mix('/css/web.css') }}">
</head>
<body class="landing-page">
<div class="container">
    <div class="col-md-12">
        @if(count($products))
            <div class="row">
                <div class="col-md-12 text-right">
                    {{ $products->links() }}
                </div>
            </div>
            <div class="row">
                @foreach ($products as $_product)
                    <div class="col-sm-4 col-md-3">
                        <div class="thumbnail">
                            <div class="caption">
                                <h3>{{ $_product->name }}</h3>
                                <div class="desc-cont">
                                    {{ str_limit($_product->description, 100) }}
                                </div>
                                <span class="text-right action-buttons">
                                        <a href="#" class="btn btn-primary"><i
                                                    class="glyphicon glyphicon-circle-arrow-right"></i>&nbsp;view</a>
                                        <a href="#" class="btn btn-primary"><i class="glyphicon glyphicon-usd"></i>&nbsp;Bid</a>
                                    </span>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
            <div class="row">
                <div class="col-md-12 text-right">
                    {{ $products->links() }}
                </div>
            </div>
        @else
            <div class="row">
                <div class="col-md-12">
                    <div class="well well-sm"><p class="text-center">No products found</p></div>
                </div>
            </div>
        @endif
    </div>
</div>
<script src="{{ asset('js/app.js') }}"></script>
<script src="{{ asset('js/plugins.js') }}"></script>
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Easy Bids') }}</title>
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>

@include('partials.nav')

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 main">
            @yield('content')
        </div>
    </div>
</div>
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/plugins.js') }}"></script>
</body>
</html>

resources/views/layouts/login.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Easy Bids') }}</title>
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>

@include('partials.nav')

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 main">
            @yield('content')
        </div>
    </div>
</div>
<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
<script src="{{ asset('js/plugins.js') }}"></script>
</body>
</html>

resources/views/partials/nav.blade.php
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">
                {{ config('app.name', 'Easy Bids') }}
            </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                @if (!Auth::guest())
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    Logout
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
                @endif
            </ul>
        </div>
    </div>
</nav>

resources/views/partials/sidenav.blade.php
<div class="col-sm-3 col-md-2 sidebar">
    <ul class="nav nav-sidebar">
        <li class="active"><a href="/dashboard">Dashboard <span class="sr-only">(current)</span></a></li>
        <li><a href="/product/create">Add product</a></li>
        <li><a href="#">Bids history</a></li>
    </ul>
</div>

resources/views/product/create.blade.php
@extends('layouts.app')

@section('content')
    @if (session('message'))
        <div class="alert alert-success">
            {{ session('message') }}
        </div>
    @endif

    <ol class="breadcrumb">
        <li><a href="/dashboard">Home</a></li>
        <li class="active">Products</li>
    </ol>

    <h1 class="page-header">Create</h1>
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="row">
        <div class="col-md-8">
            {!! Form::open(['url' => route('product.store'),  'method' => 'post']) !!}
            <div class="form-group">
                <label for="inputName">Name</label>
                {{Form::text('name', '', ['class' => 'form-control', 'id' => 'inputName'])}}
            </div>
            <div class="form-group">
                <label for="inputPrice">Price</label>
                {{Form::text('price', '', ['class' => 'form-control', 'id' => 'inputPrice'])}}
            </div>
            <div class="form-group">
                <label for="inputSku">Sku</label>
                {{Form::text('sku', '', ['class' => 'form-control', 'id' => 'inputSku'])}}
            </div>
            <div class="form-group">
                <label for="inputDescription">Description</label>
                {{Form::textarea('description', '', ['class' => 'form-control', 'id' => 'inputDescription'])}}
            </div>
            <div class="form-group text-right">
                <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-thumbs-up"></i>&nbsp;Create</button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.app')

@section('content')
@if (session('message'))
<div class="alert alert-success">
    {{ session('message') }}
</div>
@endif

<ol class="breadcrumb">
    <li><a href="#">Home</a></li>
    <li class="active">Products</li>
</ol>

<h1 class="page-header">Edit</h1>
<p><small></small></p>
@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<div class="row">
    <div class="col-md-8">
        {!! Form::open(['url' => route('product.update', $product->id),  'method' => 'put']) !!}
        <div class="form-group">
            <label for="inputName">Name</label>
            {{Form::text('name', $product->name, ['class' => 'form-control', 'id' => 'inputName'])}}
        </div>
        <div class="form-group">
            <label for="inputPrice">Price</label>
            {{Form::text('price', $product->price, ['class' => 'form-control', 'id' => 'inputPrice'])}}
        </div>
        <div class="form-group">
            <label for="inputSku">Sku</label>
            {{Form::text('sku', $product->sku, ['class' => 'form-control', 'id' => 'inputSku'])}}
        </div>
        <div class="form-group">
            <label for="inputDescription">Description</label>
            {{Form::textarea('description', $product->description, ['class' => 'form-control', 'id' => 'inputDescription'])}}
        </div>
        <div class="form-group text-right">
            <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-thumbs-up"></i>&nbsp;Update</button>
        </div>
        {!! Form::close() !!}
    </div>
</div>
@endsection

resources/views/product/list.blade.php
<p class="text-right">
    <a href="/product/create" class="btn btn-default"><i class="glyphicon glyphicon-plus"></i>&nbsp;Add new product</a>
</p>
<hr>
@if(count($products))
    <div class="table-wrapper">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>SKU</th>
                    <th>Price</th>
                    <th class="text-right">Date created</th>
                    <th class="text-right">Last updated</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php $key = 0; ?>
                @foreach ($products as $_product)
                    @php($key++)
                        <tr>
                            <td>{{ $key }}</td>
                            <td>{{ $_product->name }}</td>
                            <td>{{ $_product->sku }}</td>
                            <td>{{ $_product->price }}</td>
                            <td class="text-right">{{ $_product->created_at }}</td>
                            <td class="text-right">{{ $_product->updated_at }}</td>
                            <td class="text-right">
                                <a href="/product/view/{{ $_product->id }}"><i class="material-icons" data-toggle="tooltip" data-placement="top" title="View">pageview</i></a>
                                <a href="/product/edit/{{ $_product->id }}" ><i class="material-icons" data-toggle="tooltip" data-placement="top" title="Edit">mode_edit</i></a>
                                <a class="delete-item" data-name="{{ $_product->name }}" data-url="/product/delete/{{ $_product->id }}" href="#"><i class="material-icons" data-toggle="tooltip" data-placement="top" title="Delete">delete</i></a>
                            </td>
                        </tr>
                        @endforeach
                </tbody>
            </table>
        </div>
    </div>
@else
    <div class="well well-sm"><p class="text-center">No products found</p></div>
@endif